/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.*;
import java.net.*;
import modelo.*;

/**
 *
 * @author Victor
 */
public class ChatClient extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public ChatClient(String nombreC) {
        initComponents();
        this.nombreC = nombreC;
        lblnombre.setText("Bienvenid@ " + nombreC);
        entrada("Estableciendo conexion. Por favor espere...");
        try {
            socket = new Socket("127.0.0.1", 9999);
            entrada("Connectado. " /*+ socket.getInetAddress().getHostName()*/);
            open();
        } catch (UnknownHostException uhe) {
            entrada("Servidor desconocido: " + uhe.getMessage());
        } catch (IOException ioe) {
            entrada("Excepcion inesperada: " + ioe.getMessage());
        }
    }

    public void open() {
        try {
            canalSalida = new DataOutputStream(socket.getOutputStream());
            cliente = new ChatClientThread(this, socket);
        } catch (IOException ioe) {
            entrada("Error abriendo el canal de salida: " + ioe);
        }
    }

    public void close() {
        try {
            if (canalSalida != null) {
                canalSalida.close();
            }
            if (socket != null) {
                socket.close();
            }
        } catch (IOException ioe) {
            entrada("Error cerrando...");
        }
        cliente.close();
        cliente.stop();
    }

    public void handle(String msg) {
        if (msg.equals(nombreC + ": chiao")) {
            entrada("desconectando...");
            close();
        } else {
            entrada(msg);
        }
    }

    public void enviar() {
        if (!txtaIntro.getText().trim().equals("")) {
            try {
                if (txtaIntro.getText().equalsIgnoreCase("chiao")) {
                    canalSalida.writeUTF(txtaIntro.getText().trim());
                } else {
                    canalSalida.writeUTF(nombreC + ": " + txtaIntro.getText().trim());
                }
                canalSalida.flush();
                txtaIntro.setText("");
            } catch (IOException ioe) {
                entrada("Error al enviar: " + ioe.getMessage());
                close();
            }
        }
    }

    public void entrada(String msg) {
        txtaEntrada.append(msg + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnvio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaIntro = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaEntrada = new javax.swing.JTextArea();
        lblnombre = new javax.swing.JLabel();

        setClosable(true);

        btnEnvio.setText("Enviar");
        btnEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvioActionPerformed(evt);
            }
        });

        txtaIntro.setColumns(20);
        txtaIntro.setLineWrap(true);
        txtaIntro.setRows(5);
        txtaIntro.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtaIntro);

        txtaEntrada.setEditable(false);
        txtaEntrada.setColumns(20);
        txtaEntrada.setLineWrap(true);
        txtaEntrada.setRows(5);
        txtaEntrada.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtaEntrada);

        lblnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnombre.setText("Bienvenid@");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnvio)
                        .addContainerGap(37, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblnombre)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnEnvio)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvioActionPerformed
        enviar();
    }//GEN-LAST:event_btnEnvioActionPerformed

    private String nombreC;
    private DataOutputStream canalSalida = null;
    private Socket socket = null;
    private ChatClientThread cliente = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextArea txtaEntrada;
    private javax.swing.JTextArea txtaIntro;
    // End of variables declaration//GEN-END:variables

}
