/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Dimension;
import java.awt.Point;
import java.net.*;
import modelo.*;

/**
 *
 * @author Victor
 */
public class ChatCliente extends javax.swing.JInternalFrame  {

    /**
     * Creates new form Cliente
     */
    public ChatCliente(String nombreC) {
        initComponents();
        this.nombreC = nombreC;
        lblnombre.setText("Bienvenid@ " + nombreC); 
        cliente = new ChatClientThread(this);
        cliente.start();
    }

    public String salida(){
        return txtaIntro.getText();
    }

    public void setCliente(ChatClientThread cliente) {
        this.cliente = cliente;
    }
    
    
    
    public String getNombreC(){
        return this.nombreC;
    }

    public void entrada(String msg) {
        txtaEntrada.append(msg + "\n");
        txtaEntrada.setCaretPosition(txtaEntrada.getDocument().getLength());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnvio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaIntro = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaEntrada = new javax.swing.JTextArea();
        lblnombre = new javax.swing.JLabel();
        btnDesco = new javax.swing.JButton();

        setClosable(true);

        btnEnvio.setText("Enviar");
        btnEnvio.setEnabled(false);
        btnEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvioActionPerformed(evt);
            }
        });

        txtaIntro.setColumns(20);
        txtaIntro.setLineWrap(true);
        txtaIntro.setRows(5);
        txtaIntro.setWrapStyleWord(true);
        txtaIntro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaIntroKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtaIntro);

        jScrollPane2.setAutoscrolls(true);

        txtaEntrada.setEditable(false);
        txtaEntrada.setColumns(20);
        txtaEntrada.setLineWrap(true);
        txtaEntrada.setRows(5);
        txtaEntrada.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtaEntrada);

        lblnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnombre.setText("Bienvenid@");

        btnDesco.setText("Desconectar");
        btnDesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnvio)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblnombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDesco))
                            .addComponent(jScrollPane2))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(btnDesco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnEnvio)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvioActionPerformed
        cliente.enviarDatos(2, txtaIntro.getText().trim());
        btnEnvio.setEnabled(false);
    }//GEN-LAST:event_btnEnvioActionPerformed

    private void btnDescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescoActionPerformed
        if (cliente!=null){
            cliente.enviarDatos(3, "");
            cliente.interrupt();
        }
        cliente.setConectado(false);
    }//GEN-LAST:event_btnDescoActionPerformed

    private void txtaIntroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaIntroKeyPressed
        if (!txtaIntro.getText().trim().equals("") && cliente != null) {
            btnEnvio.setEnabled(true);
            if (evt.getKeyCode() == 10) {
                cliente.enviarDatos(2, txtaIntro.getText().trim());
                txtaIntro.setText("");
                btnEnvio.setEnabled(false);
            }else if (evt.getKeyCode() == 8 && txtaIntro.getText().length() == 1 )
                btnEnvio.setEnabled(false);
        }
    }//GEN-LAST:event_txtaIntroKeyPressed
    
    private ChatClientThread cliente = null;
    private String nombreC;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesco;
    private javax.swing.JButton btnEnvio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextArea txtaEntrada;
    private javax.swing.JTextArea txtaIntro;
    // End of variables declaration//GEN-END:variables

}
