/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Graficos.Grafico;
import java.util.ArrayList;
import modelo.Infectado;
import modelo.InfectadoDAO;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author David
 */
public class GraficosIG extends javax.swing.JInternalFrame {

    /**
     * Creates new form GraficosIG
     */
    public GraficosIG() {
        initComponents();
        InfectadoDAO antesList = new InfectadoDAO();
        ArrayList<Infectado> list = antesList.listadoInf("0");
        Grafico graf = new Grafico();
        this.graficoR = graf.rela(list);
        this.graficoE = graf.edad(list);
        this.graficoD = graf.departamentos(list);
        this.graficoS = graf.estado(list);
        this.jDesktopPane1.add(graficoR);
        this.jDesktopPane1.add(graficoE);
        this.jDesktopPane1.add(graficoD);
        this.jDesktopPane1.add(graficoS);
        graficoR.setBounds(0, 0, 715, 400);
        graficoE.setBounds(0, 410, 715, 400);
        graficoD.setBounds(725, 0, 715, 400);
        graficoS.setBounds(725, 410, 715, 400);
    }

    public void agregarGraf(ChartPanel graficoR, ChartPanel graficoE, ChartPanel graficoD, ChartPanel graficoS) {
        limpiar();
        this.jDesktopPane1.add(graficoR);
        this.jDesktopPane1.add(graficoE);
        this.jDesktopPane1.add(graficoD);
        this.jDesktopPane1.add(graficoS);
        graficoR.setBounds(0, 0, 715, 400);
        graficoE.setBounds(0, 410, 715, 400);
        graficoD.setBounds(725, 0, 715, 400);
        graficoS.setBounds(725, 410, 715, 400);
    }

    public void limpiar() {
        this.jDesktopPane1.remove(jDesktopPane1.getComponent(1));
        this.jDesktopPane1.remove(jDesktopPane1.getComponent(1));
        this.jDesktopPane1.remove(jDesktopPane1.getComponent(1));
        this.jDesktopPane1.remove(jDesktopPane1.getComponent(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private ChartPanel graficoR;
    private ChartPanel graficoE;
    private ChartPanel graficoD;
    private ChartPanel graficoS;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
